In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
np.__version__

'1.21.0'

In [4]:
pd.__version__

'1.3.2'

In [5]:
df = pd.read_csv('data.csv')

In [6]:
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [7]:
# The average price of BMW
df[df['Make'] == 'BMW']['MSRP'].mean()

61546.76347305389

In [8]:
# Number of missing values in "Engine HP" after 2015
df[df['Year'] > 2014]['Engine HP'].isnull().sum()

51

In [9]:
# Does the mean change after filling missing values?
round(df['Engine HP'].mean(), 2)

249.39

In [10]:
df['Engine HP'] = df['Engine HP'].fillna(249.38607007176023)
round(df['Engine HP'].mean(), 2)

249.39

In [11]:
# Question 6 "Engine HP", "Engine Cylinders", "highway MPG".
RR = df[df['Make'] == 'Rolls-Royce']

In [12]:
df_RR = RR[['Engine HP', 'Engine Cylinders', 'highway MPG']]
df_RR = df_RR.drop_duplicates()
X = df_RR.to_numpy()

In [13]:
XTX = X.T.dot(X)

In [14]:
XTX

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [15]:
XTXinv = np.linalg.inv(XTX)

In [16]:
XTXinv

array([[ 5.17815728e-05,  9.06587044e-04, -1.92984188e-03],
       [ 9.06587044e-04,  1.05723058e-01, -8.87084092e-02],
       [-1.92984188e-03, -8.87084092e-02,  1.05900809e-01]])

In [17]:
XTXinv.dot(XTX)

array([[ 1.00000000e+00,  4.93528829e-16,  5.71157704e-16],
       [ 1.91513472e-14,  1.00000000e+00,  1.22402088e-14],
       [-7.71049891e-14, -1.42663659e-14,  1.00000000e+00]])

In [18]:
round(np.sum(XTXinv), 4)

0.0322

In [19]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [20]:
w = XTXinv.dot(X.T).dot(y)

In [21]:
w

array([ 0.19989598, 31.02612262, 31.65378877])

The value of the first w element is: 0.1999